language: php

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8

env:
  - CC=clang
  - CC=gcc-4.8
  - CC=gcc-4.8 VALGRIND=1

install:
  - if [ "$VALGRIND" -eq 1 ]; then sudo apt-get install -qq valgrind; export TEST_PHP_ARGS="-m"; fi
  - sudo apt-get install -qq $CC
  - if [ "$VALGRIND" -eq 1 ]; then valgrind --version; export TEST_PHP_ARGS="-m"; fi
  - $CC --version

php:
  - '7.0'
  - nightly

before_script:
 - cc --version
 - (export CC; phpize && ./configure --disable-runkit-sandbox && make)

script:
 - ci/run_tests.sh
