language: php

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8

sudo: false

php:
  - '7.0'
  - nightly

before_script:
 - cc --version
 - (export CC=gcc-4.8; phpize && ./configure --disable-runkit-sandbox && make)

script:
 - ci/run_tests.sh
